# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: classify.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'classify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63lassify.proto\x12\x08\x63lassify\"[\n\x0f\x43lassifyRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\x12\x0f\n\x07signals\x18\x04 \x03(\t\",\n\x0cRankedSignal\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"\xe4\x01\n\x10\x43lassifyResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x15\n\rclassifier_id\x18\x02 \x01(\t\x12\x16\n\x0emodel_revision\x18\x03 \x01(\t\x12\x1a\n\x12tokenizer_revision\x18\x04 \x01(\t\x12\x19\n\x11taxonomy_revision\x18\x05 \x01(\t\x12.\n\x06status\x18\x06 \x01(\x0e\x32\x1e.classify.ClassificationStatus\x12&\n\x06ranked\x18\x07 \x03(\x0b\x32\x16.classify.RankedSignal*c\n\x14\x43lassificationStatus\x12%\n!CLASSIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x0b\n\x07\x41\x42STAIN\x10\x02\x12\x0f\n\x0bUNAVAILABLE\x10\x03\x32M\n\x08\x43lassify\x12\x41\n\x08\x43lassify\x12\x19.classify.ClassifyRequest\x1a\x1a.classify.ClassifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLASSIFICATIONSTATUS']._serialized_start=398
  _globals['_CLASSIFICATIONSTATUS']._serialized_end=497
  _globals['_CLASSIFYREQUEST']._serialized_start=28
  _globals['_CLASSIFYREQUEST']._serialized_end=119
  _globals['_RANKEDSIGNAL']._serialized_start=121
  _globals['_RANKEDSIGNAL']._serialized_end=165
  _globals['_CLASSIFYRESPONSE']._serialized_start=168
  _globals['_CLASSIFYRESPONSE']._serialized_end=396
  _globals['_CLASSIFY']._serialized_start=499
  _globals['_CLASSIFY']._serialized_end=576
# @@protoc_insertion_point(module_scope)
